name: selfrec
channels:
- pytorch
- nvidia
- defaults
- conda-forge
dependencies:
- scipy=1.13.1
- safetensors=0.4.4
- numba=0.60.0
- numpy=1.26.4 
- pyyaml=6.0.1
- pytorch=2.1.0
- pytorch-cuda=11.8
- pandas=2.2.2
- scikit-learn=1.5.1
- transformers=4.44.1
- pillow=10.4.0
- matplotlib=3.9.2
- ipykernel=6.28.0
- python-dotenv=0.21.0
- pip:
  - jq==1.8.0
  - qywx-bot==1.4
  - sentence-transformers==3.1.1
  - flash-attn==2.6.3
  