name: selfrec
channels:
- pytorch
- nvidia
- defaults
- conda-forge
dependencies:
- python=3.9.19
- langchain-community=0.2.16
- scipy=1.13.1
- safetensors=0.4.4
- numba=0.60.0
- numpy=1.26.4 
- pyyaml=6.0.1
- pytorch=1.13.1
- pytorch-cuda=11.7
- pandas=2.2.2
- scikit-learn=1.5.1
- transformers=4.44.1
- pillow=10.4.0
- ipykernel=6.28.0
- python-dotenv=0.21.0